Resources:
  S3ForStaticSite:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: jiwanheo.com
      VersioningConfiguration:
        Status: Enabled # Enable versioning if needed
      WebsiteConfiguration:
        IndexDocument: index.html
      Tags:
        - Key: Project
          Value: jiwanheo.com

Outputs:
  S3ForStaticSiteArn:
    Description: The ARN of the S3 bucket for the static site
    Value: !GetAtt S3ForStaticSite.Arn
    Export:
      Name: S3ForStaticSiteArn