name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main # Triggers on pushes to the phase4 branch

jobs:
  checkout_and_setup:
    runs-on: ubuntu-latest
    outputs:
      aws-credentials-configured: ${{ steps.configure_aws.outcome }}
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configure AWS Credentials
      - name: Configure AWS credentials
        id: configure_aws
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Replace with your desired region

      # Step 3: Upload repository as artifact
      - name: Upload repository
        uses: actions/upload-artifact@v3
        with:
          name: repo-files
          path: .

  deploy_s3:
    runs-on: ubuntu-latest
    needs: checkout_and_setup
    steps:
      # Step 1: Download artifact
      - name: Download repository artifact
        uses: actions/download-artifact@v3
        with:
          name: repo-files

      - name: Debug working directory without anything
        run: |
          pwd
          ls -R
          
      # Step 3: Deploy CloudFormation Stack for S3
      - name: Deploy S3 Stack
        run: |
          aws cloudformation deploy \
            --template-file infra/s3bucket.yml \
            --stack-name S3BucketStack \
            --capabilities CAPABILITY_NAMED_IAM \
            --region us-east-1