name: Deploy Hugo to S3

on:
  push:
    branches:
      - main # Trigger on push to main branch
  pull_request:
    branches:
      - main # Trigger on PRs targeting the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest # This specifies the environment the job will run in

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Checkout the code from your repository

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.139.4" # Use the latest Hugo version
          extended: true

      - name: Install PostCSS
        run: |
          npm install postcss postcss-cli autoprefixer # Install PostCSS and any required plugins

      - name: Build the site
        run: |
          cd site  # Navigate to the 'site' directory
          hugo  # Build the site (outputs to 'public/' by default)

      - name: Deploy to S3
        run: |
          aws s3 sync site/public/ s3://jiwanheo.com --exact-timestamps --delete  # Deploy the 'public' folder to S3
        
      # Work-around to CloudFront not serving index.html file under subdirectories.   
      - name: Duplicate index.html in subdirectories
        run: |
          for o in $(aws s3api list-objects --bucket jiwanheo.com --query "Contents[?contains(Key, '/index.html')].Key" --output text); do
            n=$(echo ${o} | sed -e "s/\/index.html//g")
            aws s3 cp s3://jiwanheo.com/${o} s3://jiwanheo.com/${n}
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-2"